### ISSUE TITLE
Investigate block time in tendermint

### ISSUE THREAD

**Issue by sunify** [parsec-labs/parsec-node#46]
Currently, blocks are created too often and nobody has seen a block with >1 tx. Also, we need some time to submit period (every 32 blocks). Because of the short block time, we haven't time for a period submission.

Maybe related to #45

**Comment by eezcjkr** [comment]
So there is a config parameter called timeoutCommit, which we should be able to use to control block time. It is located in .lotion/<netowrk_id>/config/config.toml. 

However, I tried setting it to a high number, but I still got multiple blocks in a single second. This could be due to the config not being read by lotion, needs more research though.

**Comment by sunify** [comment]
Correction:
managed to make a block with 5 txs
